version: "3"
services:
  usuarios:
    build: ./usuarios
    depends_on:
      - db
    links:
      - db
    ports:
      - "3001:3001"
  aptos:
    build: ./aptos
    depends_on:
      - db
    links:
      - db
    ports:
      - "3002:3002"
  postulaciones:
    build: ./postulaciones
    depends_on:
      - db
    links:
      - db
      - usuarios
      - aptos
    ports:
      - "3003:3003"
  haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    depends_on:
      - microweb1
      - microweb2
    ports:
      - "80:80"
  microweb1:
    build:
      context: ./microweb
      dockerfile: Dockerfile
    depends_on:
      - usuarios
      - aptos
      - postulaciones
  microweb2:
    build:
      context: ./microweb
      dockerfile: Dockerfile
    depends_on:
      - usuarios
      - aptos
      - postulaciones
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./db/data:/var/lib/mysql-files/"
      - ./db:/docker-entrypoint-initdb.d/:ro
