version: "3"
services:
  usuarios:
    image: usuarios
    depends_on:
      - db
    links:
      - db
    ports:
      - "3001:3001"
  aptos:
    image: aptos
    depends_on:
      - db
    links:
      - db
    ports:
      - "3002:3002"
  postulaciones:
    image: postulaciones
    depends_on:
      - db
    links:
      - db
      - usuarios
      - aptos
    ports:
      - "3003:3003"
  haproxy:
    image: haproxy
    depends_on:
      - microweb
    ports:
      - "80:80"
    links:
      - microweb
  microweb:
    image: microweb
    depends_on:
      - usuarios
      - aptos
      - postulaciones
    links:
      - usuarios
      - aptos
      - postulaciones
    ports:
      - "1080:80"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./db/data:/var/lib/mysql-files/"
      - ./db:/docker-entrypoint-initdb.d/:ro
